baseURL = 'https://megacephalo.github.io/megacephalo-tech-blog/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hugo-bearcub"

# Generate a nice robots.txt for SEO
defaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "Megacephalo Tech Blog"
    languageName = "en-US 🇺🇸"
    LanguageCode = "en-US"
    contentDir = "content"
    [languages.en.params]
      madeWith = "Carpe Diem"


[menu]

[[menu.main]]
  name = "Posts"
  pageRef = "/posts-en"
  weight = 1

[[menu.main]]
  name = "About me"
  pageRef = "/about_me"
  weight = 2

[[menu.main]]
  name = "Contact me"
  pageRef = "/contact_me"
  weight = 3


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Required for rendering HTML in Markdown

  [markup.highlight]
    codeFences = true
    guessSyntax = true


[params]
  # The description of your website
  description = "The simple blog to share my learning on Robotics"

  # The path to your favicon
  # favicon = "images/favicon.png"

  # These images will show up when services want to generate a preview of a link
  # to your site. Ignored if `generateSocialCard = true`. For more information
  # about previews, see https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph
  # images = ["images/share.webp"]

  # This title is used as the site_name on the Hugo's internal opengraph
  # structured data template
  title = "Megacephalo Tech Blog"

  # Dates are displayed following the format below. For more information about
  # formatting, see https://gohugo.io/functions/format/
  dateFormat = "2006-01-02"

  # If your blog is multilingual but you haven't translated a page, this theme
  # will create a disabled link. By setting `hideUntranslated` to true, you can
  # have the theme simply not show any link
  hideUntranslated = false

  # (EXPERIMENTAL) This theme has two options for its CSS styles: "original" and
  # "herman". The former is what you see on Bear Cub's demo (an optimized
  # version of Hugo Bear Blog), while the latter has a more modern look based on
  # Herman Martinus's version of the Blogster Minimal theme for Astro.
  themeStyle = "original"

  # (EXPERIMENTAL) This theme is capable of dynamically generating social cards
  # for posts that don't have `images` defined in their front matter; By setting
  # `generateSocialCard` to false, you can prevent this behavior. For more
  # information see layouts/partials/social_card.html
  generateSocialCard = true

  math = true


  # Social media. Delete any item you aren't using to make sure it won't show up
  # in your website's metadata.
  [params.social]
    linkedin = "https://www.linkedin.com/in/charlyhuang/"
    github = "https://github.com/Megacephalo"

  # Author metadata. This is mostly used for the RSS feed of your site, but the
  # email is also added to the footer of each post. You can hide the "reply to"
  # link by using a `hideReply` param in front matter.
  [params.author]
    name = "Charly Huang" # Your name as shown in the RSS feed metadata
    email = "charly.charlongo@gmail.com" # Added to the footer so readers can reply to posts