baseURL = 'https://megacephalo.github.io/megacephalo-tech-blog/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hugo-bearcub"

# Generate a nice robots.txt for SEO
defaultContentLanguage = "en"



